[package]
name = "near-bigint"
version = "1.0.0"
authors = ["jack the dev <joao@hackachain.io>"]
edition = "2021"
license = "MIT"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0" }
uint = "0.9.3"
paste = "1.0.9"

[dev-dependencies]
rstest = "0.14.0"

[profile.release]
codegen-units = 1
# s = optimize for binary size ("z" would additionally turn off loop vectorization)
opt-level = "z"
# link time optimization
lto = true
debug = false
panic = "abort"
overflow-checks = true