[package]
name = "hideyourcash-contract-near"
version = "0.1.0"
authors = ["jack the dev"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0", features = ["unstable"] }
near-bigint = {path = "../../contract-libraries/near_bigint"}
near_mimc = {path = "../../contract-libraries/near_mimc"}
near_plonk_verifier = {path = "../../contract-libraries/plonk_verifier/near_plonk_verifier"}
hapi-near-connector = "0.1"

[dev-dependencies]
rstest = "0.14.0"