[package]
name = "contract"
version = "0.1.0"
authors = ["Near Inc <hello@near.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0", features = ["unstable"] }
near-bigint = {path = "../../contract-libraries/near_bigint"}
near_mimc = {path = "../../contract-libraries/near_mimc"}
near_groth16_verifier = {path = "../../contract-libraries/groth_verifier/near_groth16_verifier"}

[dev-dependencies]
rstest = "0.14.0"