[package]
name = "registry"
version = "0.1.0"
authors = ["Jack the dev"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0" }
near-bigint = { path = "../../contract-libraries/near_bigint" }
near_mimc = { path = "../../contract-libraries/near_mimc" }
hyc-events = { path = "../../contract-libraries/hyc_events" }

[dev-dependencies]
rstest = "0.14.0"
