[package]
name = "near_groth16_verifier"
version = "1.0.0"
authors = ["jack the dev <joao@hackachain.io>"]
edition = "2021"
license = "MIT"
keywords = ["near_protocol", "groth16", "zero_knowledge", "cryptography"]
categories = [
    "wasm",
    "cryptography",
    "cryptography::cryptocurrencies"
]
description = "Groth16 proof verifier implementation for Near Protocol smart Contracts"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0", features = ["unstable"] }
near-bigint = { path = "../../near_bigint", version = "1.0.0" }

[dev-dependencies]
rstest = "0.14.0"