[package]
name = "authorizer"
version = "0.1.0"
authors = ["p-destri"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
near-bigint = {path = "../../contract-libraries/near_bigint"}
mimc = {path = "../../contract-libraries/mimc"}
rust_verifier = {path = "../../contract-libraries/groth_verifier/rust_verifier"}

[dev-dependencies]
rstest = "0.14.0"