name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_RELAYER: ${{ secrets.VITE_RELAYER }}
  VITE_CONTRACT: 13f7a05920e419a4b8c0hyctest.testnet
  VITE_NEAR_NETWORK: testnet
  VITE_API_GRAPHQL_URL: https://api.thegraph.com/subgraphs/name/veigajoao/test_hyc
  VITE_NEAR_NODE_URL: https://rpc.testnet.near.org
  VITE_GTM_ID: ${{ secrets.VITE_GTM_ID }}
on: pull_request

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'

      - name: Installing Dependencies
        run: yarn

      - name: Relayer Tests
        run: yarn contracts relayer:setup

      - name: Building Relayer
        run: yarn relayer build

      - name: Fucking evens
        run: echo env

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ztY_5KVqTuVDv2Nnl7Nl9TtpVT-9MToTWeMXa13H
          command: publish --name dev-relayer --env env

          workingDirectory: 'packages/relayer'
          secrets: |
              RELAYER_FEE
              NEAR_NETWORK
              ACCOUNT_ID
              PRIVATE_KEY
              HYC_CONTRACT
              RPC_URL
              TEST_ENV
        env:
          TEST_ENV: "foo"
          RELAYER_FEE: "0"
          NEAR_NETWORK: "testnet"
          ACCOUNT_ID: ${{ env.TESTNET_RELAYER_ACCOUNT_ID }}
          PRIVATE_KEY: ${{ env.TESTNET_RELAYER_PRIVATE_KEY }}
          HYC_CONTRACT: ${{ env.TESTNET_HYC_CONTRACT }}
          RPC_URL: "https://rpc.testnet.near.org"
