name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_RELAYER: ${{ secrets.VITE_RELAYER }}
  VITE_CONTRACT: c28a0b8ab1211fa0bec1hyctest.testnet
  VITE_NEAR_NETWORK: testnet
  VITE_API_GRAPHQL_URL: https://api.thegraph.com/subgraphs/name/veigajoao/test_hyc3
  VITE_NEAR_NODE_URL: https://rpc.testnet.near.org
  VITE_GTM_ID: ${{ secrets.VITE_GTM_ID }}
on: pull_request

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  relayer-deploy:
    runs-on: ubuntu-latest
    name: Relayer Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: yarn relayer deploy --name dev-relayer
          secrets: |
              RELAYER_FEE
              NEAR_NETWORK
              ACCOUNT_ID
              PRIVATE_KEY
              HYC_CONTRACT
              RPC_URL
        env:
          RELAYER_FEE: "0"
          NEAR_NETWORK: "testnet"
          ACCOUNT_ID: ${{ secrets.TESTNET_RELAYER_ACCOUNT_ID }}
          PRIVATE_KEY: ${{ secrets.TESTNET_RELAYER_PRIVATE_KEY }}
          HYC_CONTRACT: ${{ secrets.TESTNET_HYC_CONTRACT }}
          RPC_URL: "https://rpc.testnet.near.org"
