name: Deploy PR to Staging

on:
  repository_dispatch:
    types: [deploy-command]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-pr-to-staging:
    runs-on: ubuntu-latest
    env:
      # vercel envs
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      THE_GRAPH_TOKEN: ${{ secrets.THE_GRAPH_TOKEN }}

      VITE_GTM_ID: ${{ secrets.VITE_GTM_ID }}
      VITE_NEAR_NODE_URL: https://rpc.mainnet.near.org/
      VITE_CONTRACT: registry.hideyourcash.near
      VITE_API_GRAPHQL_URL: https://api.thegraph.com/subgraphs/name/hack-a-chain/hyc_staging
      VITE_NEAR_NETWORK: mainnet
      VITE_RELAYER_NETWORK: staging
      VITE_RELAYER_URL: https://staging-relayer.hideyourcash.workers.dev

      HYC_CONTRACT_PREFIX: hideyourcash.near
      HYC_START_BLOCK: 87518288

      VITE_TRACES_SAMPLE_RATE: 0
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}

      # relayer envs
      PRIVATE_KEY: ${{ secrets.PROD_RELAYER_SECRET_KEY }}
      ACCOUNT_ID: relayer.hideyourcash.near
      RELAYER_FEE: "0.003"
      BASE_STORAGE_FEE: "0.1"
      RELAYER_NAME: "staging-relayer"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - name: Fetch circom
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "iden3/circom"
          version: "tags/v2.1.3"
          file: "circom-linux-amd64"
          target: "circom"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Give circom exec permissions
        run: chmod +x circom

      - name: Add circom to path
        run: echo $(pwd) >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Install Yarn Globally
        run: npm install -g yarn

      - name: Installing Dependencies
        run: yarn

      - name: Installing TheGraph
        run: yarn global add @graphprotocol/graph-cli

      - name: Signin on TheGraph
        run: graph auth --product=hosted-service "$THE_GRAPH_TOKEN"

      - name: Deploy The graph
        run: yarn subgraph deploy:staging

      - name: Building Relayer
        run: yarn relayer build

      - name: Set Relayer Variables
        env: 
          NEAR_NETWORK: ${{ env.VITE_NEAR_NETWORK }}
          RPC_URL: ${{ env.VITE_NEAR_NODE_URL }}
          RELAYER_URL: ${{ env.VITE_RELAYER_URL }}
          HYC_CONTRACT: ${{ env.VITE_CONTRACT }} 
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
        run: yarn relayer populate:envs


      - name: Publish Relayer
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --name staging-relayer --keep-vars
          workingDirectory: 'packages/relayer'

      - name: Compile circuits
        run: yarn circuits circuit:setup:plonk

      - name: Pull vercel setup
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: >
          vercel
          deploy
          --prebuilt
          --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            Build finished and sent to Vercel to finish the deploy.
          reactions: rocket

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket

