name: Production Deploy
env:
  # common envs
  HYC_CONTRACT: "13f7a05920e419a4b8c0hyctest.testnet"
  NEAR_NETWORK: "testnet"
  RPC_URL: "https://rpc.testnet.near.org"

  # vercel envs
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  # front envs
  VITE_RELAYER: ${{ secrets.VITE_RELAYER }}
  VITE_GTM_ID: ${{ secrets.VITE_GTM_ID }}
  VITE_RELAYER_URL: https://prod-relayer.hideyourcash.workers.dev/
  VITE_API_GRAPHQL_URL: "https://api.thegraph.com/subgraphs/name/veigajoao/test_hyc"

  # relayer envs
  RELAYER_FEE: "0.10"
  ACCOUNT_ID: ${{ secrets.RELAYER_ACCOUNT_ID }}
  PRIVATE_KEY: ${{ secrets.RELAYER_PRIVATE_KEY }}

on: pull_request
# on:
#   push:
#     branches:
#       - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  relayer_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'

      - name: Installing Dependencies
        run: yarn

      - name: Building Relayer
        run: yarn relayer build

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --name prod-relayer
          workingDirectory: 'packages/relayer'
          secrets: |
              RELAYER_FEE
              NEAR_NETWORK
              ACCOUNT_ID
              PRIVATE_KEY
              HYC_CONTRACT
              RPC_URL
              RELAYER_URL
        env:
          RELAYER_FEE: ${{ env.RELAYER_FEE }}
          NEAR_NETWORK: ${{ env.NEAR_NETWORK }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
          PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
          HYC_CONTRACT: ${{ env.HYC_CONTRACT }}
          RPC_URL: ${{ env.RPC_URL }}
          RELAYER_URL: "https://prod-relayer.hideyourcash.workers.dev"

  vercel_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch circom
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'iden3/circom'
          version: 'tags/v2.1.3'
          file: 'circom-linux-amd64'
          target: 'circom'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Give circom exec permissions
        run: chmod +x circom

      - name: Add circom to path
        run: echo $(pwd) >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Install Yarn Globally
        run: npm install -g yarn

      - name: Installing Dependencies
        run: yarn

      - name: Compile circuits
        run: yarn circuits circuit:setup:plonk

      - name: Pull vercel setup
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        env:
            VITE_CONTRACT: ${{ env.HYC_CONTRACT }}
            VITE_NEAR_NODE_URL: ${{ env.RPC_URL }}
            VITE_NEAR_NETWORK: ${{ env.NEAR_NETWORK }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: >
          vercel
          deploy
          --prebuilt
          --prod
          --token=${{ secrets.VERCEL_TOKEN }}
