name: Vercel Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_RELAYER: ${{ secrets.VITE_RELAYER }}
  VITE_CONTRACT: c28a0b8ab1211fa0bec1hyctest.testnet
  VITE_NEAR_NETWORK: testnet
  VITE_API_GRAPHQL_URL: https://api.thegraph.com/subgraphs/name/veigajoao/test_hyc3
  VITE_NEAR_NODE_URL: https://rpc.testnet.near.org
on:
  push:
    branches:
      - main

jobs:
  full_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch circom
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'iden3/circom'
          version: 'tags/v2.1.3'
          file: 'circom-linux-amd64'
          target: 'circom'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Give circom exec permissions
        run: chmod +x circom

      - name: Add circom to path
        run: echo $(pwd) >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Install Yarn Globally
        run: npm install -g yarn

      - name: Installing Dependencies
        run: yarn

      - name: Compile circuits
        run: yarn circuits circuit:setup:plonk

      - name: Pull vercel setup
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: >
          vercel
          deploy
          --prebuilt
          --prod
          --token=${{ secrets.VERCEL_TOKEN }}
